### ISSUE TITLE
Improve cells bonding algorithm

### ISSUE THREAD

**Issue by olegthelilfix** [david-d25/cell-sandbox#3]
We need to improve cells bonding algorithm.

**Comment by david-d25** [comment]
Problem clarification:
When the cell with existing connection divides, he is replaces with two child cells. The problem is, the children do not inherit the existing connections, so they always disconnect from their neighbors:
![Image](https://user-images.githubusercontent.com/27444607/194773384-60990e42-a745-4056-ae8e-f899373fc448.png)

The right behavior for the cell in the previous example would be:
![Image](https://user-images.githubusercontent.com/27444607/194773720-8f37aa27-4737-40d7-bd4f-397e42a7c240.png)

I will later provide a more detailed explanation about how connections should be processed when cell divides.
